#!/usr/bin/env php
<?php

use Portiere\Portiere;

if (is_file($autoload = __DIR__ . '/vendor/autoload.php')) {
    require $autoload;
} elseif (is_file($autoload = __DIR__ . '/../../autoload.php')) {
    require $autoload;
} else {
    exit(1);
}

$app = new Portiere('Portiere', '0.3.0');
$app->run();
