#!/usr/bin/env php
<?php

if (is_file($autoload = __DIR__ . '/vendor/autoload.php')) {
    require $autoload;
} elseif (is_file($autoload = __DIR__ . '/../../autoload.php')) {
    require $autoload;
} else {
    exit(1);
}

$app = new VhostBuilder\Tool\VhostCreateTool('Vhost Builder', '0.3.0');
$app->run();
